import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as SecureStore from 'expo-secure-store';
import * as ImagePicker from 'expo-image-picker';
import { NavigationContainer, useFocusEffect } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { SafeAreaProvider, useSafeAreaInsets } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Claim, Item, User, itemDate, itemName, itemOwner, imageUri, request } from './src/api';
import { Button, Empty, Field, IconButton, ItemCard, StatusPill } from './src/components';
import { C, CATEGORIES, shadow } from './src/theme';

type Session = { token: string; user: User };
const Auth = createContext<{ session: Session | null; save: (value: Session | null) => Promise<void> }>({ session: null, save: async () => {} });
const useAuth = () => useContext(Auth);
const Stack = createNativeStackNavigator();
const Tabs = createBottomTabNavigator();
function today() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
function Page({ children }: { children: React.ReactNode }) { const insets = useSafeAreaInsets(); return <ScrollView style={s.page} contentContainerStyle={{ paddingTop: insets.top + 12, paddingBottom: insets.bottom + 35 }} keyboardShouldPersistTaps="handled">{children}</ScrollView>; }
function Head({ title, subtitle, back }: { title: string; subtitle?: string; back?: () => void }) { return <View style={s.head}>{back && <IconButton icon="arrow-back" label="Go back" onPress={back} />}<View style={{ flex: 1, marginLeft: back ? 4 : 0 }}><Text style={s.h1}>{title}</Text>{subtitle && <Text style={s.muted}>{subtitle}</Text>}</View></View>; }
function Note({ message, info = false }: { message: string; info?: boolean }) { return <View style={[s.note, { backgroundColor: info ? C.bluePale : C.dangerPale }]}><Ionicons name={info ? 'information-circle-outline' : 'alert-circle-outline'} size={20} color={info ? C.blue : C.danger} /><Text style={{ color: info ? C.blueDark : C.danger, flex: 1, lineHeight: 20 }}>{message}</Text></View>; }
function Loading() { return <View style={{ padding: 42 }}><ActivityIndicator size="large" color={C.blue} /></View>; }
function Row({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={s.row}><View style={s.rowIcon}><Ionicons name={icon} size={19} color={C.blue} /></View><View><Text style={s.small}>{label}</Text><Text style={s.rowValue}>{value}</Text></View></View>; }

function AuthScreen() {
  const { save } = useAuth(); const [register, setRegister] = useState(false), [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function submit() { setError(''); if (register && name.trim().length < 2) return setError('Enter your full name.'); if (!/^\S+@\S+\.\S+$/.test(email.trim())) return setError('Enter a valid email address.'); if (password.length < (register ? 8 : 1)) return setError(register ? 'Use at least 8 password characters.' : 'Enter your password.'); setBusy(true); try { const result = await request<Session>(register ? '/auth/register' : '/auth/login', undefined, { method: 'POST', body: JSON.stringify({ name, email: email.trim().toLowerCase(), password }) }); await save(result); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  return <Page><LinearGradient colors={[C.navy, C.blue]} style={s.authHero}><View style={s.logo}><Ionicons name="search" size={29} color={C.white} /></View><Text style={s.brand}>CampusFind</Text><Text style={s.heroSub}>Good things find their way back.</Text></LinearGradient><View style={s.authCard}><Text style={s.h2}>{register ? 'Join CampusFind' : 'Welcome back'}</Text><Text style={s.body}>Reuniting lost belongings with their owners at SLIIT.</Text>{!!error && <Note message={error} />}{register && <Field label="Full name" value={name} onChangeText={setName} placeholder="Your name" textContentType="name" />}<Field label="Email address" value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address" autoCapitalize="none" textContentType="emailAddress" /><Field label="Password" value={password} onChangeText={setPassword} placeholder="Enter password" secureTextEntry textContentType={register ? 'newPassword' : 'password'} /><Button title={register ? 'Create account' : 'Sign in'} onPress={submit} loading={busy} /><Pressable style={s.toggle} accessibilityRole="button" onPress={() => { setRegister(!register); setError(''); }}><Text style={s.body}>{register ? 'Already have an account? ' : 'New here? '}<Text style={s.link}>{register ? 'Sign in' : 'Create account'}</Text></Text></Pressable></View></Page>;
}

function Discover({ navigation }: any) {
  const { session } = useAuth(); const [items, setItems] = useState<Item[]>([]), [search, setSearch] = useState(''), [category, setCategory] = useState('All'), [busy, setBusy] = useState(true), [error, setError] = useState('');
  const load = useCallback(async () => { if (!session) return; setBusy(true); setError(''); try { const q = new URLSearchParams(); if (search) q.set('search', search); if (category !== 'All') q.set('category', category); setItems((await request<{ items: Item[] }>(`/items?${q}`, session.token)).items); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }, [session?.token, search, category]);
  useFocusEffect(useCallback(() => { const t = setTimeout(load, search ? 300 : 0); return () => clearTimeout(t); }, [load, search]));
  return <Page><View style={s.pad}><View style={s.welcome}><View><Text style={s.overline}>SLIIT CAMPUS</Text><Text style={s.h1}>Find what matters.</Text><Text style={s.muted}>Hello, {session?.user.name.split(' ')[0]}</Text></View><View style={s.avatar}><Text style={s.avatarText}>{session?.user.name[0]?.toUpperCase()}</Text></View></View><LinearGradient colors={[C.navy, C.blue]} style={s.banner}><View style={{ flex: 1 }}><Text style={s.bannerSmall}>LOST SOMETHING?</Text><Text style={s.bannerTitle}>Let's bring it{String.fromCharCode(10)}back home.</Text><Text style={s.bannerBody}>Browse what your campus community has found.</Text></View><View style={s.bannerIcon}><Ionicons name="search" size={46} color={C.white} /></View></LinearGradient><View style={s.search}><Ionicons name="search-outline" size={21} color={C.blue} /><TextInput value={search} onChangeText={setSearch} placeholder="Search item or location" placeholderTextColor="#71869B" accessibilityLabel="Search item or location" style={{ flex: 1, fontSize: 15, color: C.text }} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{['All', ...CATEGORIES].map(c => <Pressable key={c} accessibilityRole="button" accessibilityState={{ selected: category === c }} onPress={() => setCategory(c)} style={[s.chip, category === c && s.chipOn]}><Text style={[s.chipText, category === c && { color: C.white }]}>{c}</Text></Pressable>)}</ScrollView><View style={s.sectionLine}><Text style={s.h2}>Recently found</Text><Text style={s.muted}>{items.length} items</Text></View>{error ? <><Note message={error} /><Button title="Try again" kind="secondary" onPress={load} /></> : busy ? <Loading /> : items.length ? items.map(item => <ItemCard key={item._id} item={item} onPress={() => navigation.navigate('ItemDetail', { id: item._id })} />) : <Empty icon="search-outline" title="Nothing found yet" body="Try another search or category. New items will appear here." />}</View></Page>;
}

function MyItems({ navigation }: any) { const { session } = useAuth(); const [items, setItems] = useState<Item[]>([]), [busy, setBusy] = useState(true), [error, setError] = useState(''); const load = useCallback(async () => { setBusy(true); setError(''); try { setItems((await request<{ items: Item[] }>('/items?mine=true', session?.token)).items); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }, [session?.token]); useFocusEffect(useCallback(() => { load(); }, [load])); return <Page><View style={s.pad}><Head title="My items" subtitle="Manage the things you've found" /><Button title="Post a found item" icon="add-circle-outline" onPress={() => navigation.navigate('ItemForm', {})} /><View style={{ height: 24 }} />{error ? <Note message={error} /> : busy ? <Loading /> : items.length ? items.map(item => <ItemCard key={item._id} item={item} onPress={() => navigation.navigate('ItemDetail', { id: item._id })} />) : <Empty icon="cube-outline" title="No items posted" body="Found something on campus? Post it here to help its owner." />}</View></Page>; }

function ItemDetail({ navigation, route }: any) {
  const { session } = useAuth(); const [item, setItem] = useState<Item | null>(null), [busy, setBusy] = useState(true), [error, setError] = useState(''); const load = useCallback(async () => { setBusy(true); setError(''); try { setItem((await request<{ item: Item }>(`/items/${route.params.id}`, session?.token)).item); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }, [route.params.id, session?.token]); useFocusEffect(useCallback(() => { load(); }, [load]));
  const remove = () => Alert.alert('Delete item?', 'Items with claims cannot be deleted.', [{ text: 'Keep' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await request(`/items/${item?._id}`, session?.token, { method: 'DELETE' }); navigation.goBack(); } catch (e: any) { Alert.alert('Unable to delete', e.message); } } }]);
  const mine = !!item && itemOwner(item) === session?.user.id;
  return <Page><View style={s.pad}><Head title="Item details" back={() => navigation.goBack()} />{error ? <Note message={error} /> : busy ? <Loading /> : item && <><View style={s.detailImage}>{item.imageUrl ? <Image source={{ uri: imageUri(item.imageUrl) }} style={{ width: '100%', height: '100%' }} /> : <Ionicons name="cube-outline" size={72} color={C.blue} />}</View><View style={s.detailRow}><Text style={s.overline}>{item.category.toUpperCase()}</Text><StatusPill status={item.status} /></View><Text style={s.detailTitle}>{item.title}</Text><Text style={s.body}>{item.description}</Text><View style={s.infoCard}><Row icon="location-outline" label="Found at" value={item.foundLocation} /><Row icon="calendar-outline" label="Date found" value={itemDate(item.foundDate)} /><Row icon="person-outline" label="Posted by" value={itemName(item)} /></View><View style={s.actions}>{mine ? <><Button title="Review claims" icon="documents-outline" onPress={() => navigation.navigate('ClaimsForItem', { itemId: item._id, title: item.title })} /><Button title="Edit item" kind="secondary" onPress={() => navigation.navigate('ItemForm', { item })} disabled={item.status !== 'Available'} /><Button title="Delete item" kind="ghost" onPress={remove} /></> : item.status === 'Available' ? <Button title="This is mine — submit a claim" icon="hand-left-outline" onPress={() => navigation.navigate('ClaimForm', { itemId: item._id, title: item.title })} /> : <Note message="This item has already been returned." info />}</View></>}</View></Page>;
}

function ItemForm({ navigation, route }: any) {
  const { session } = useAuth(); const original: Item | undefined = route.params?.item;
  const [title, setTitle] = useState(original?.title || ''), [description, setDescription] = useState(original?.description || ''), [category, setCategory] = useState(original?.category || 'Other'), [location, setLocation] = useState(original?.foundLocation || ''), [date, setDate] = useState(original?.foundDate?.slice(0, 10) || today()); const [asset, setAsset] = useState<ImagePicker.ImagePickerAsset | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function pick() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError('Allow photo access to choose an image.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [4, 3], quality: .7 }); if (!result.canceled) { if ((result.assets[0].fileSize || 0) > 3 * 1024 * 1024) return setError('Choose an image under 3 MB.'); setAsset(result.assets[0]); setError(''); } }
  async function save() { setError(''); if (title.trim().length < 3 || description.trim().length < 15 || location.trim().length < 3 || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return setError('Complete all fields. Description needs 15 characters; use YYYY-MM-DD for date.'); if (date > today()) return setError('Found date cannot be in the future.'); setBusy(true); try { const body = { title: title.trim(), description: description.trim(), category, foundLocation: location.trim(), foundDate: date }; const result = await request<{ item: Item }>(original ? `/items/${original._id}` : '/items', session?.token, { method: original ? 'PATCH' : 'POST', body: JSON.stringify(body) }); if (asset) { const form = new FormData(); form.append('image', { uri: asset.uri, name: asset.fileName || 'item.jpg', type: asset.mimeType || 'image/jpeg' } as any); await request(`/items/${result.item._id}/image`, session?.token, { method: 'POST', body: form }); } navigation.replace('ItemDetail', { id: result.item._id }); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }
  return <Page><View style={s.pad}><Head title={original ? 'Edit item' : 'Post found item'} subtitle="Help the owner recognize it" back={() => navigation.goBack()} />{!!error && <Note message={error} />}<Pressable onPress={pick} accessibilityRole="button" accessibilityLabel="Choose item photo" style={s.photoPicker}>{asset?.uri || original?.imageUrl ? <Image source={{ uri: asset?.uri || imageUri(original?.imageUrl || '') }} style={{ width: '100%', height: '100%' }} /> : <><Ionicons name="camera-outline" size={34} color={C.blue} /><Text style={s.pickerTitle}>Add an item photo</Text><Text style={s.small}>JPG, PNG or WebP · up to 3 MB</Text></>}</Pressable><Field label="Item title" value={title} onChangeText={setTitle} placeholder="e.g. Blue wireless headphones" /><Field label="Description" value={description} onChangeText={setDescription} placeholder="Brand, color and visible details" multiline /><Text style={s.fieldLabel}>Category</Text><View style={s.wrap}>{CATEGORIES.map(c => <Pressable key={c} accessibilityRole="button" accessibilityState={{ selected: category === c }} onPress={() => setCategory(c)} style={[s.chip, category === c && s.chipOn]}><Text style={[s.chipText, category === c && { color: C.white }]}>{c}</Text></Pressable>)}</View><Field label="Where was it found?" value={location} onChangeText={setLocation} placeholder="e.g. Malabe library, second floor" /><Field label="Date found (YYYY-MM-DD)" value={date} onChangeText={setDate} placeholder="2026-10-01" /><Button title={original ? 'Save changes' : 'Publish item'} onPress={save} loading={busy} /></View></Page>;
}

function ClaimForm({ navigation, route }: any) { const { session } = useAuth(); const existing: Claim | undefined = route.params?.claim; const [details, setDetails] = useState(existing?.identifyingDetails || ''), [busy, setBusy] = useState(false), [error, setError] = useState(''); async function save() { if (details.trim().length < 15) return setError('Provide at least 15 characters of identifying details.'); setBusy(true); setError(''); try { await request(existing ? `/claims/${existing._id}` : '/claims', session?.token, { method: existing ? 'PATCH' : 'POST', body: JSON.stringify(existing ? { identifyingDetails: details.trim() } : { itemId: route.params.itemId, identifyingDetails: details.trim() }) }); Alert.alert('Saved', existing ? 'Your claim was updated.' : 'The finder can now review your claim.', [{ text: 'OK', onPress: () => navigation.navigate('Main', { screen: 'My Claims' }) }]); } catch (e: any) { setError(e.message); } finally { setBusy(false); } } return <Page><View style={s.pad}><Head title={existing ? 'Edit claim' : 'Claim this item'} subtitle={route.params.title} back={() => navigation.goBack()} /><Note message="Share a detail only the owner would know. Only the finder can read it." info />{!!error && <Note message={error} />}<Field label="How can the finder identify your item?" value={details} onChangeText={setDetails} placeholder="Describe a private mark, contents or other detail" multiline /><Button title={existing ? 'Save claim' : 'Submit claim'} onPress={save} loading={busy} /></View></Page>; }

function ClaimsList({ navigation, route, owner = false }: any) { const { session } = useAuth(); const [claims, setClaims] = useState<Claim[]>([]), [busy, setBusy] = useState(true), [error, setError] = useState(''); const load = useCallback(async () => { setBusy(true); setError(''); try { setClaims((await request<{ claims: Claim[] }>(owner ? `/claims?itemId=${route.params.itemId}` : '/claims', session?.token)).claims); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }, [owner, route.params?.itemId, session?.token]); useFocusEffect(useCallback(() => { load(); }, [load])); return <Page><View style={s.pad}><Head title={owner ? 'Item claims' : 'My claims'} subtitle={owner ? route.params.title : 'Track your recovery requests'} back={owner ? () => navigation.goBack() : undefined} />{error ? <><Note message={error} /><Button title="Try again" kind="secondary" onPress={load} /></> : busy ? <Loading /> : claims.length ? claims.map(claim => { const item = typeof claim.itemId === 'string' ? null : claim.itemId; return <Pressable key={claim._id} onPress={() => navigation.navigate('ClaimDetail', { id: claim._id, owner })} accessibilityRole="button" accessibilityLabel={`View ${claim.status} claim for ${item?.title || 'item'}`} style={s.claimCard}><View style={s.claimLine}><View style={s.claimIcon}><Ionicons name="receipt-outline" size={22} color={C.blue} /></View><View style={{ flex: 1 }}><Text style={s.claimTitle}>{item?.title || 'Found item'}</Text><Text style={s.muted}>{owner ? (typeof claim.claimantId === 'string' ? 'Claimant' : claim.claimantId.name) : itemDate(claim.createdAt)}</Text></View><Ionicons name="chevron-forward" size={18} color={C.muted} /></View><View style={s.claimBottom}><StatusPill status={claim.status} /><Text style={s.link}>View details</Text></View></Pressable>; }) : <Empty icon="receipt-outline" title="No claims yet" body={owner ? 'Claims for this item will appear here.' : 'Find an item that belongs to you and submit a claim.'} />}</View></Page>; }
function MyClaims(props: any) { return <ClaimsList {...props} />; }
function ClaimsForItem(props: any) { return <ClaimsList {...props} owner />; }

function ClaimDetail({ navigation, route }: any) { const { session } = useAuth(); const [claim, setClaim] = useState<Claim | null>(null), [busy, setBusy] = useState(true), [error, setError] = useState(''); const load = useCallback(async () => { setBusy(true); setError(''); try { setClaim((await request<{ claim: Claim }>(`/claims/${route.params.id}`, session?.token)).claim); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }, [route.params.id, session?.token]); useFocusEffect(useCallback(() => { load(); }, [load])); function action(status: string) { Alert.alert(`${status} claim?`, status === 'Approved' ? 'The item will be marked returned. Other pending claims will be rejected.' : 'This changes the claim status.', [{ text: 'Go back' }, { text: 'Continue', onPress: async () => { try { await request(`/claims/${claim?._id}/status`, session?.token, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (e: any) { Alert.alert('Action failed', e.message); } } }]); } function remove() { Alert.alert('Delete claim?', 'This cannot be undone.', [{ text: 'Keep it' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await request(`/claims/${claim?._id}`, session?.token, { method: 'DELETE' }); navigation.goBack(); } catch (e: any) { Alert.alert('Unable to delete', e.message); } } }]); } const item = claim && typeof claim.itemId !== 'string' ? claim.itemId : null; return <Page><View style={s.pad}><Head title="Claim details" back={() => navigation.goBack()} />{error ? <Note message={error} /> : busy ? <Loading /> : claim && <><View style={s.claimDetailTop}><View style={s.claimLargeIcon}><Ionicons name="hand-left-outline" size={35} color={C.blue} /></View><Text style={s.detailTitle}>{item?.title || 'Found item'}</Text><StatusPill status={claim.status} /></View><View style={s.infoCard}><Row icon="calendar-outline" label="Submitted" value={itemDate(claim.createdAt)} /><Row icon="person-outline" label="Claimant" value={typeof claim.claimantId === 'string' ? 'Campus member' : claim.claimantId.name} /></View><Text style={s.fieldLabel}>Identifying details</Text><Text style={s.detailsBox}>{claim.identifyingDetails}</Text><View style={s.actions}>{claim.status === 'Pending' && (route.params.owner ? <><Button title="Approve and mark returned" onPress={() => action('Approved')} /><Button title="Reject claim" kind="secondary" onPress={() => action('Rejected')} /></> : <><Button title="Edit details" kind="secondary" onPress={() => navigation.navigate('ClaimForm', { claim, title: item?.title })} /><Button title="Cancel claim" kind="ghost" onPress={() => action('Cancelled')} /></>)}{claim.status !== 'Approved' && <Button title="Delete claim" kind="ghost" onPress={remove} />}</View></>}</View></Page>; }

function Profile() { const { session, save } = useAuth(); return <Page><View style={s.pad}><Head title="Your profile" subtitle="Your CampusFind account" /><LinearGradient colors={[C.navy, C.blue]} style={s.profile}><View style={s.profileIcon}><Text style={s.profileInitial}>{session?.user.name[0]?.toUpperCase()}</Text></View><Text style={s.profileName}>{session?.user.name}</Text><Text style={s.profileEmail}>{session?.user.email}</Text></LinearGradient><Text style={s.h2}>About CampusFind</Text><Text style={[s.body, { marginTop: 8, marginBottom: 25 }]}>Made for the SLIIT campus community. If an item is yours, send a private identifying detail for the finder to review.</Text><Button title="Sign out" kind="secondary" icon="log-out-outline" onPress={() => Alert.alert('Sign out?', 'You can sign in again at any time.', [{ text: 'Stay' }, { text: 'Sign out', onPress: () => save(null) }])} /><Text style={s.footer}>CampusFind · SLIIT student project</Text></View></Page>; }
function MainTabs() { return <Tabs.Navigator screenOptions={({ route }) => ({ headerShown: false, tabBarActiveTintColor: C.blue, tabBarInactiveTintColor: C.muted, tabBarStyle: { backgroundColor: C.white, borderTopColor: C.line, height: Platform.OS === 'android' ? 67 : 86, paddingTop: 7 }, tabBarLabelStyle: { fontSize: 11, fontWeight: '700', paddingBottom: Platform.OS === 'android' ? 8 : 1 }, tabBarIcon: ({ color, size }) => <Ionicons name={({ Explore: 'compass-outline', 'My Items': 'cube-outline', 'My Claims': 'receipt-outline', Profile: 'person-outline' } as any)[route.name]} size={size} color={color} /> })}><Tabs.Screen name="Explore" component={Discover} /><Tabs.Screen name="My Items" component={MyItems} /><Tabs.Screen name="My Claims" component={MyClaims} /><Tabs.Screen name="Profile" component={Profile} /></Tabs.Navigator>; }
export default function App() { const [session, update] = useState<Session | null>(null), [ready, setReady] = useState(false); useEffect(() => { SecureStore.getItemAsync('campusfind.session').then(async value => { if (value) { const saved: Session = JSON.parse(value); try { const result = await request<{ user: User }>('/auth/me', saved.token); update({ ...saved, user: result.user }); } catch { await SecureStore.deleteItemAsync('campusfind.session'); } } }).finally(() => setReady(true)); }, []); async function save(value: Session | null) { update(value); if (value) await SecureStore.setItemAsync('campusfind.session', JSON.stringify(value)); else await SecureStore.deleteItemAsync('campusfind.session'); } return <SafeAreaProvider><Auth.Provider value={{ session, save }}><NavigationContainer><StatusBar style="dark" />{!ready ? <View style={s.boot}><ActivityIndicator size="large" color={C.blue} /><Text style={s.bootText}>CampusFind</Text></View> : !session ? <AuthScreen /> : <Stack.Navigator screenOptions={{ headerShown: false, contentStyle: { backgroundColor: C.bg } }}><Stack.Screen name="Main" component={MainTabs} /><Stack.Screen name="ItemDetail" component={ItemDetail} /><Stack.Screen name="ItemForm" component={ItemForm} /><Stack.Screen name="ClaimForm" component={ClaimForm} /><Stack.Screen name="ClaimsForItem" component={ClaimsForItem} /><Stack.Screen name="ClaimDetail" component={ClaimDetail} /></Stack.Navigator>}</NavigationContainer></Auth.Provider></SafeAreaProvider>; }

const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: C.bg }, pad: { paddingHorizontal: 20 }, head: { flexDirection: 'row', alignItems: 'center', minHeight: 56, marginBottom: 20 }, h1: { color: C.navy, fontSize: 27, fontWeight: '800', letterSpacing: -.5 }, h2: { color: C.navy, fontSize: 21, fontWeight: '800' }, muted: { color: C.muted, fontSize: 13, marginTop: 3 }, body: { color: C.muted, fontSize: 15, lineHeight: 23 }, small: { color: C.muted, fontSize: 12 }, overline: { color: C.orangeText, fontSize: 11, fontWeight: '900', letterSpacing: 1.2 }, link: { color: C.blue, fontWeight: '800', fontSize: 13 },
  authHero: { height: 270, paddingHorizontal: 26, paddingTop: 55 }, logo: { width: 58, height: 58, backgroundColor: C.orange, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 18 }, brand: { color: C.white, fontSize: 34, fontWeight: '900' }, heroSub: { color: '#E5F1FF', fontSize: 16, marginTop: 6 }, authCard: { backgroundColor: C.white, borderRadius: 26, padding: 24, marginHorizontal: 16, marginTop: -30, marginBottom: 30, ...shadow }, toggle: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 12 }, note: { flexDirection: 'row', gap: 9, padding: 13, borderRadius: 13, marginBottom: 17 },
  welcome: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }, avatar: { width: 46, height: 46, borderRadius: 15, backgroundColor: C.orangePale, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: C.orangeText, fontWeight: '800', fontSize: 20 }, banner: { minHeight: 190, borderRadius: 23, padding: 22, flexDirection: 'row', alignItems: 'center', marginBottom: 22 }, bannerSmall: { color: '#FFB985', fontSize: 11, fontWeight: '800', letterSpacing: 1 }, bannerTitle: { color: C.white, fontSize: 25, fontWeight: '900', lineHeight: 31, marginTop: 8 }, bannerBody: { color: '#E5F1FF', fontSize: 12, lineHeight: 18, marginTop: 10, maxWidth: 210 }, bannerIcon: { width: 85, height: 85, borderRadius: 28, backgroundColor: C.orange, alignItems: 'center', justifyContent: 'center' }, search: { minHeight: 55, borderRadius: 16, backgroundColor: C.white, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 15, borderWidth: 1, borderColor: C.line, marginBottom: 13 }, chip: { minHeight: 39, paddingHorizontal: 14, borderRadius: 20, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' }, chipOn: { backgroundColor: C.blue, borderColor: C.blue }, chipText: { color: C.navy, fontSize: 13, fontWeight: '700' }, sectionLine: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginTop: 23, marginBottom: 15 },
  detailImage: { height: 258, borderRadius: 23, backgroundColor: C.bluePale, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', marginBottom: 20 }, detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, detailTitle: { color: C.navy, fontSize: 28, fontWeight: '900', lineHeight: 34, marginVertical: 11 }, infoCard: { backgroundColor: C.white, borderRadius: 19, padding: 15, marginVertical: 22, ...shadow }, row: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingVertical: 8 }, rowIcon: { width: 37, height: 37, borderRadius: 12, backgroundColor: C.bluePale, alignItems: 'center', justifyContent: 'center' }, rowValue: { color: C.navy, fontSize: 14, fontWeight: '700', marginTop: 2 }, actions: { gap: 11, marginBottom: 20 },
  photoPicker: { height: 180, backgroundColor: C.bluePale, borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#A9C8ED', borderRadius: 19, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', marginBottom: 24 }, pickerTitle: { color: C.navy, fontSize: 15, fontWeight: '800', marginVertical: 7 }, fieldLabel: { color: C.navy, fontSize: 14, fontWeight: '800', marginBottom: 10 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 22 },
  claimCard: { backgroundColor: C.white, borderRadius: 19, padding: 16, marginBottom: 12, ...shadow }, claimLine: { flexDirection: 'row', alignItems: 'center', gap: 12 }, claimIcon: { width: 47, height: 47, borderRadius: 15, backgroundColor: C.bluePale, alignItems: 'center', justifyContent: 'center' }, claimTitle: { color: C.navy, fontSize: 16, fontWeight: '800' }, claimBottom: { marginTop: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, claimDetailTop: { alignItems: 'center', marginTop: 18 }, claimLargeIcon: { width: 80, height: 80, borderRadius: 25, backgroundColor: C.bluePale, alignItems: 'center', justifyContent: 'center' }, detailsBox: { backgroundColor: C.white, borderRadius: 17, padding: 18, color: C.text, fontSize: 15, lineHeight: 23, marginBottom: 22 },
  profile: { alignItems: 'center', borderRadius: 23, padding: 30, marginBottom: 28 }, profileIcon: { width: 74, height: 74, borderRadius: 23, backgroundColor: C.orangeText, alignItems: 'center', justifyContent: 'center' }, profileInitial: { color: C.white, fontSize: 33, fontWeight: '900' }, profileName: { color: C.white, fontSize: 22, fontWeight: '800', marginTop: 15 }, profileEmail: { color: '#D7E9FF', fontSize: 13, marginTop: 4 }, footer: { textAlign: 'center', color: C.muted, marginTop: 34, fontSize: 12 }, boot: { flex: 1, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' }, bootText: { color: C.blue, fontSize: 27, fontWeight: '900', marginTop: 18 },
});
