require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const { rateLimit } = require('express-rate-limit');
const { connectDB } = require('./db');
const { errorHandler } = require('./middleware/common');
const app = express();
app.set('trust proxy', 1);
app.disable('x-powered-by'); app.use(helmet()); app.use(cors()); app.use(express.json({ limit: '100kb' }));
app.use('/api/auth', rateLimit({ windowMs: 15 * 60 * 1000, limit: 50, standardHeaders: 'draft-8', legacyHeaders: false }));
app.get('/api/health', async (req, res, next) => { try { await connectDB(); res.json({ status: 'ok', service: 'CampusFind API' }); } catch (error) { next(error); } });
app.use('/api', async (req, res, next) => { try { await connectDB(); next(); } catch (error) { next(error); } });
app.get('/api/images/:id', require('./storage').serveImage);
app.use('/api/auth', require('./routes/auth'));
app.use('/api/items', require('./routes/items'));
app.use('/api/claims', require('./routes/claims'));
app.use('/api/admin', require('./routes/admin'));
app.use((req, res) => res.status(404).json({ error: 'Route not found.' })); app.use(errorHandler);
module.exports = app;
